package com.banco.models;
// Generated 26-ene-2020 17:52:41 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name = "cuenta", catalog = "si_banco")
public class Cuenta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCuenta;
	private Cliente cliente;
	private String descripcion;
	private BigDecimal montoInicial;
	private Date creacion;
	private BigDecimal saldo;
	private boolean estado;
	private List<Transacciones> transaccioneses = new ArrayList<>();

	public Cuenta() {
		this.creacion = new Date();
	}

	public Cuenta(Cliente cliente, String descripcion, BigDecimal montoInicial, Date creacion, BigDecimal saldo,
			boolean estado) {
		this.cliente = cliente;
		this.descripcion = descripcion;
		this.montoInicial = montoInicial;
		this.creacion = creacion;
		this.saldo = saldo;
		this.estado = estado;
	}

	public Cuenta(Cliente cliente, String descripcion, BigDecimal montoInicial, Date creacion, BigDecimal saldo,
			boolean estado, List<Transacciones> transaccioneses) {
		this.cliente = cliente;
		this.descripcion = descripcion;
		this.montoInicial = montoInicial;
		this.creacion = creacion;
		this.saldo = saldo;
		this.estado = estado;
		this.transaccioneses = transaccioneses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_cuenta", unique = true, nullable = false)
	public Integer getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(Integer idCuenta) {
		this.idCuenta = idCuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "descripcion", nullable = false, length = 60)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "monto_inicial", nullable = false, precision = 10)
	public BigDecimal getMontoInicial() {
		return this.montoInicial;
	}

	public void setMontoInicial(BigDecimal montoInicial) {
		this.montoInicial = montoInicial;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creacion", nullable = false, length = 10)
	public Date getCreacion() {
		return this.creacion;
	}

	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

	@Column(name = "saldo", nullable = false, precision = 10)
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuenta")
	public List<Transacciones> getTransaccioneses() {
		return this.transaccioneses;
	}

	public void setTransaccioneses(List<Transacciones> transaccioneses) {
		this.transaccioneses = transaccioneses;
	}

}
