package com.banco.models;
// Generated 25-ene-2020 9:44:09 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TpTransaccion generated by hbm2java
 */
@Entity
@Table(name = "tp_transaccion", catalog = "si_banco")
public class TpTransaccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idTpTra;
	private String descripcionTpt;
	private List<Transacciones> transaccioneses = new ArrayList<>();

	public TpTransaccion() {
	}

	public TpTransaccion(int idTpTra, String descripcionTpt) {
		this.idTpTra = idTpTra;
		this.descripcionTpt = descripcionTpt;
	}

	public TpTransaccion(int idTpTra, String descripcionTpt, List<Transacciones> transaccioneses) {
		this.idTpTra = idTpTra;
		this.descripcionTpt = descripcionTpt;
		this.transaccioneses = transaccioneses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_tp_tra", unique = true, nullable = false)
	public int getIdTpTra() {
		return this.idTpTra;
	}

	public void setIdTpTra(int idTpTra) {
		this.idTpTra = idTpTra;
	}

	@Column(name = "descripcion_tpt", nullable = false, length = 65)
	public String getDescripcionTpt() {
		return this.descripcionTpt;
	}

	public void setDescripcionTpt(String descripcionTpt) {
		this.descripcionTpt = descripcionTpt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpTransaccion")
	public List<Transacciones> getTransaccioneses() {
		return this.transaccioneses;
	}

	public void setTransaccioneses(List<Transacciones> transaccioneses) {
		this.transaccioneses = transaccioneses;
	}

}
