package com.banco.models;
// Generated 25-ene-2020 9:44:09 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transacciones generated by hbm2java
 */
@Entity
@Table(name = "transacciones", catalog = "si_banco")
public class Transacciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idTra;
	private Cuenta cuenta;
	private TpTransaccion tpTransaccion;
	private BigDecimal valor;
	private Date fechaTra;

	public Transacciones() {
	}

	public Transacciones(int idTra, Cuenta cuenta, TpTransaccion tpTransaccion, BigDecimal valor, Date fechaTra) {
		this.idTra = idTra;
		this.cuenta = cuenta;
		this.tpTransaccion = tpTransaccion;
		this.valor = valor;
		this.fechaTra = fechaTra;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_tra", unique = true, nullable = false)
	public int getIdTra() {
		return this.idTra;
	}

	public void setIdTra(int idTra) {
		this.idTra = idTra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cuenta", nullable = false)
	public Cuenta getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Cuenta cuenta) {
		this.cuenta = cuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo", nullable = false)
	public TpTransaccion getTpTransaccion() {
		return this.tpTransaccion;
	}

	public void setTpTransaccion(TpTransaccion tpTransaccion) {
		this.tpTransaccion = tpTransaccion;
	}

	@Column(name = "valor", nullable = false, precision = 10)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_tra", nullable = false, length = 10)
	public Date getFechaTra() {
		return this.fechaTra;
	}

	public void setFechaTra(Date fechaTra) {
		this.fechaTra = fechaTra;
	}

}
